version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - gosimple
    - gofmt
    - goimports

  settings:
    goimports:
      local-prefixes: github.com/DevTroopers-ITU/itu-minitwit

run:
  timeout: 5m

exclusions:
  rules:
    - path: _test\.go
      linters:
        - errcheck