services:
  webserver:
    build: .
    image: ghcr.io/devtroopers-itu/minitwit:latest
    ports:
      - "8080:8080"
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}

  prometheus:
    build: ./monitoring/prometheus
    ports:
      - "9090:9090"
    mem_limit: 256m
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=15d"
    depends_on:
      - webserver

  grafana:
    build: ./monitoring/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
