services:
  webserver:
    build: .
    image: ghcr.io/devtroopers-itu/minitwit:latest
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - DATABASE_URL=postgres://doadmin:${POSTGRES_PASSWORD}@db-postgresql-fra1-53911-do-user-33311270-0.k.db.ondigitalocean.com:25060/defaultdb?sslmode=require
