services:
  webserver:
    environment:
      - DATABASE_URL=postgres://postgres:testpassword@db:5432/minitwit
    depends_on:
      db:
        condition: service_healthy


  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: minitwit
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


  tests:
    image: python:3.12-slim
    depends_on:
      webserver:
        condition: service_healthy
    working_dir: /work
    volumes:
      - .:/work
    environment:
      - BASE_URL=http://webserver:8080
    command: >
      sh -c "
          pip install --upgrade pip &&
          pip install -r requirements.txt &&
          pytest python-references/minitwit_sim_api_test.py -v
        "

  clidownload:
    profiles: ["manual"]

