sonar.projectKey=DevTroopers-ITU_itu-minitwit
sonar.organization=devtroopers-itu

sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**,**/templates/**,**/static/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
